routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'view.variables'], function () {
    Auth::routes();
});

Route::group(['middleware' => ['auth', 'organization', 'view.variables']], function () {
    Route::get('/', 'HomeController@index')
        ->name('home');

    Route::get('/invitations', 'InvitationController@index')
        ->name('invitations.index');
    Route::get('/invitations/create', 'InvitationController@create')
        ->name('invitations.create');
    Route::post('/invitations', 'InvitationController@store')
        ->name('invitations.store');
    Route::delete('/invitations/{maybeExpiredInvitation}', 'InvitationController@delete')
        ->name('invitations.delete');

    Route::get('/preferences', 'PreferencesController@edit')
        ->name('preferences.edit');
    Route::put('/preferences', 'PreferencesController@update')
        ->name('preferences.update');

    Route::get('/organizations', 'OrganizationController@index')
        ->name('organizations.index');
    Route::get('/organizations/create', 'OrganizationController@create')
        ->name('organizations.create');
    Route::get('/organizations/deleted', 'OrganizationController@deleted')
        ->name('organizations.deleted');
    Route::get('/organizations/{organization}', 'OrganizationController@show')
        ->name('organizations.show');
    Route::get('/organizations/{organization}/edit', 'OrganizationController@edit')
        ->name('organizations.edit');
    Route::post('/organizations', 'OrganizationController@store')
        ->name('organizations.store');
    Route::post('/organizations/{trashedOrganization}/restore', 'OrganizationController@restore')
        ->name('organizations.restore');
    Route::post('/organizations/{organization}/switch', 'OrganizationController@switch')
        ->name('organizations.switch');
    Route::put('/organizations/{organization}', 'OrganizationController@update')
        ->name('organizations.update');
    Route::delete('/organizations/{organization}', 'OrganizationController@delete')
        ->name('organizations.delete');

    Route::get('/webhooks', 'WebhookController@index')
        ->name('webhooks.index');
    Route::get('/webhooks/create', 'WebhookController@create')
        ->name('webhooks.create');
    Route::get('/webhooks/{webhook}/edit', 'WebhookController@edit')
        ->name('webhooks.edit');
    Route::post('/webhooks', 'WebhookController@store')
        ->name('webhooks.store');
    Route::put('/webhooks/{webhook}', 'WebhookController@update')
        ->name('webhooks.update');
    Route::delete('/webhooks/{webhook}', 'WebhookController@delete')
        ->name('webhooks.delete');
    Route::post('/webhooks/{webhook}/test', 'WebhookController@test')
        ->name('webhooks.test');

    Route::get('/webhooks/{webhook}', 'WebhookCallController@index')
        ->name('webhookcalls.index');
    Route::get('/webhooks/{webhook}/calls/{call}', 'WebhookCallController@show')
        ->name('webhookcalls.show');

    Route::put('/token', 'Auth\ApiTokenController@update')->name('token.update');

    Route::get('/assets', 'AssetController@index')
        ->name('assets.index');
    Route::get('/assets/create', 'AssetController@create')
        ->name('assets.create');
    Route::get('/assets/deleted', 'AssetController@deleted')
        ->name('assets.deleted');
    Route::get('/assets/{asset:uuid}', 'AssetController@show')
        ->name('assets.show');
    Route::post('/assets', 'AssetController@store')
        ->name('assets.store');
    Route::get('/assets/{asset:uuid}/edit', 'AssetController@edit')
        ->name('assets.edit');
    Route::put('/assets/{asset:uuid}', 'AssetController@update')
        ->name('assets.update');
    Route::delete('/assets/{asset:uuid}', 'AssetController@delete')
        ->name('assets.delete');
    Route::post('/assets/{trashedAsset:uuid}/restore', 'AssetController@restore')
        ->name('assets.restore');
    Route::post('/assets/{trashedAsset:uuid}/forceDelete', 'AssetController@forceDelete')
        ->name('assets.forceDelete');

    Route::get('/assets/{asset:uuid}/prices/create', 'PriceController@create')
        ->name('prices.create');
    Route::post('/assets/{asset:uuid}/prices', 'PriceController@store')
        ->name('prices.store');
    Route::delete('/assets/{asset:uuid}/prices/{price}', 'PriceController@delete')
        ->name('prices.delete');

    Route::get('/assets/{asset:uuid}/transactions/create', 'TransactionController@create')
        ->name('transactions.create');
    Route::post('/assets/{asset:uuid}/transactions', 'TransactionController@store')
        ->name('transactions.store');
    Route::get('/assets/{asset:uuid}/transactions/{transaction}/edit', 'TransactionController@edit')
        ->name('transactions.edit');
    Route::put('/assets/{asset:uuid}/transactions/{transaction}', 'TransactionController@update')
        ->name('transactions.update');
    Route::delete('/assets/{asset:uuid}/transactions/{transaction}', 'TransactionController@delete')
        ->name('transactions.delete');

    Route::get('/assets/{asset:uuid}/values/create', 'ValueController@create')
        ->name('values.create');
    Route::post('/assets/{asset:uuid}/values', 'ValueController@store')
        ->name('values.store');

    Route::get('/allocations', 'AllocationController@index')
        ->name('allocations.index');
    Route::get('/allocations/create', 'AllocationController@create')
        ->name('allocations.create');
    Route::get('/allocations/deleted', 'AllocationController@deleted')
        ->name('allocations.deleted');
    Route::get('/allocations/{allocation}/{view}', 'AllocationController@show')
        ->where('view', implode('|', array_map(fn(AllocationViewMode $x) => $x->value, AllocationViewMode::cases())))
        ->name('allocations.show');
    Route::get('/allocations/{allocation}/value', 'AllocationController@value')
        ->name('allocations.value');
    Route::get('/allocations/{allocation}/edit', 'AllocationController@edit')
        ->name('allocations.edit');
    Route::post('/allocations', 'AllocationController@store')
        ->name('allocations.store');
    Route::post('/allocations/{trashedAllocation}/restore', 'AllocationController@restore')
        ->name('allocations.restore');
    Route::put('/allocations/{allocation}', 'AllocationController@update')
        ->name('allocations.update');
    Route::delete('/allocations/{allocation}', 'AllocationController@delete')
        ->name('allocations.delete');

    Route::get('/allocations/{allocation}/check/edit', 'AllocationCheckController@edit')
        ->name('allocations.check.edit');
    Route::put('/allocations/{allocation}/check', 'AllocationCheckController@update')
        ->name('allocations.check.update');
    Route::delete('/allocations/{allocation}/check', 'AllocationCheckController@delete')
        ->name('allocations.check.delete');

    Route::get('/imports', 'ImportController@index')
        ->name('imports.index');
    Route::get('/imports/create', 'ImportController@create')
        ->name('imports.create');
    Route::get('/imports/deleted', 'ImportController@deleted')
        ->name('imports.deleted');
    Route::get('/imports/{importConfiguration}', 'ImportController@show')
        ->name('imports.show');
    Route::get('/imports/{importConfiguration}/edit', 'ImportController@edit')
        ->name('imports.edit');
    Route::post('/imports', 'ImportController@store')
        ->name('imports.store');
    Route::post('/imports/{trashedImportConfiguration}/restore', 'ImportController@restore')
        ->name('imports.restore');
    Route::post('/imports/{importConfiguration}/run', 'ImportController@run')
        ->name('imports.run');
    Route::put('/imports/{importConfiguration}', 'ImportController@update')
        ->name('imports.update');
    Route::delete('/imports/{importConfiguration}', 'ImportController@delete')
        ->name('imports.delete');

    Route::get('/executions', 'ExecutionController@index')
        ->name('executions.index');
    Route::get('/executions/{execution}', 'ExecutionController@show')
        ->name('executions.show');
    Route::delete('/executions/{execution}', 'ExecutionController@delete')
        ->name('executions.delete');

    Route::get('/exports', 'ExportController@index')
        ->name('exports.index');
    Route::get('/exports/create', 'ExportController@create')
        ->name('exports.create');
    Route::post('/exports/run', 'ExportController@run')
        ->name('exports.run');

    Route::post('/display/graph', 'Display\DisplayController@setGraphControls')
        ->name('display.graph');

    Route::get('/notifications', 'NotificationController@index')
        ->name('notifications.index');
    Route::get('/notifications/{notification}', 'NotificationController@show')
        ->name('notifications.show');

    Route::group(['prefix' => '/admin', 'middleware' => ['can:admin-actions']], function () {
        Route::get('/', 'Admin\HomeController@index')
            ->name('admin.home');

        Route::get('/users', 'Admin\UserController@index')
            ->name('admin.users.index');
        Route::get('/users/{user}', 'Admin\UserController@show')
            ->name('admin.users.show');
        Route::post('/users/{user}/promote', 'Admin\UserController@promote')
            ->name('admin.users.promote');
        Route::post('/users/{user}/demote', 'Admin\UserController@demote')
            ->name('admin.users.demote');

        Route::get('/scheduled-checks/executions', 'Admin\ScheduledChecksController@index')

app/Models/ImportConfiguration.php
<?php

namespace App\Models;

use App\Casts\CarbonTimeZone;
use App\Enums\EntityType;
use App\Enums\InputContentType;
use App\Enums\InputMethod;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class ImportConfiguration extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'note',
        'input_method',
        'input_content_type',
        'date_format',
        'timezone',
        'url',
        'has_header_row',
        'delimiter',
        'enclosure_character',
        'escape_character',
        'entity_type',
        'parse_expression',
    ];

    protected $casts = [
        'timezone' => CarbonTimeZone::class,
        'input_method' => InputMethod::class,
        'input_content_type' => InputContentType::class,
        'entity_type' => EntityType::class,
    ];

    public function getReadableMethodAttribute(): string
    {
        if ($this->input_method === InputMethod::Download) {
            return "{$this->input_method->value} {$this->entity_type->value} {$this->input_content_type->value} from $this->url";
        }
        return "{$this->input_method->value} {$this->entity_type->value} {$this->input_content_type->value}";
    }

    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    public function asset(): BelongsTo
    {
        return $this->belongsTo(Asset::class);
    }

    public function importExecutions(): HasMany
    {
        return $this->hasMany(ImportExecution::class);
    }
}

resources/views/imports/_delete.blade.php
<?php

use App\Models\ImportConfiguration;

/** @var ImportConfiguration $importConfiguration */

?>
<div class="modal" id="deleteImportModal{{ $importConfiguration->id }}" tabindex="-1" role="dialog" aria-labelledby="deleteImportModalLabel{{ $importConfiguration->id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteImportModalLabel{{ $importConfiguration->id }}">Delete import configuration '{{ $importConfiguration->name }}'</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this import configuration? You can still undo it later.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                <form action="{{ route('imports.delete', $importConfiguration) }}" method="post">
                    @method('delete')
                    @csrf
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/imports/create.blade.php
<?php

use App\Models\ImportConfiguration;

/** @var ImportConfiguration $importConfiguration */
/** @var string[] $selectableTimezones */

?>
@extends('layouts.app')

@section('content')
    <h1>New import configuration</h1>

    <form class="needs-validation" action="{!! route('imports.store') !!}" method="post" novalidate>
        @csrf

        @include('imports._form', ['importConfiguration' => $importConfiguration, 'selectableTimezones' => $selectableTimezones])

        <button type="submit" class="btn btn-primary">Create import configuration</button>
    </form>
@endsection

resources/views/imports/deleted.blade.php
<?php

use App\Models\ImportConfiguration;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/** @var LengthAwarePaginator&ImportConfiguration[] $importConfigurations */

?>
@extends('layouts.app')

@section('content')
    <h1>Deleted import configurations</h1>

    <div class="table-responsive">
        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>Method</th>
                <th>Date deleted</th>
                <th>Operations</th>
            </tr>

            @forelse($importConfigurations as $importConfiguration)
                <tr>
                    <td>
                        {{ $importConfiguration->name }}
                    </td>
                    <td>
                        {{ $importConfiguration->readable_method }}
                    </td>
                    <td>
                        {{ $importConfiguration->deleted_at->ago() }}
                    </td>
                    <td>
                        <form action="{{ route('imports.restore', $importConfiguration) }}" method="post">
                            @csrf
                            <button type="submit" class="btn btn-primary">Restore</button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr><td colspan="999">There are no deleted import configurations.</td></tr>
            @endforelse
        </table>

        {!! $importConfigurations->links() !!}
    </div>
@endsection

resources/views/imports/edit.blade.php
<?php

use App\Models\ImportConfiguration;

/** @var ImportConfiguration $importConfiguration */
/** @var string[] $selectableTimezones */

?>
@extends('layouts.app')

@section('content')
    <h1>Edit '{{ $importConfiguration->getOriginal('name') }}'</h1>

    <form class="needs-validation" action="{!! route('imports.update', $importConfiguration) !!}" method="post" novalidate>
        @method('put')
        @csrf

        @include('imports._form', ['importConfiguration' => $importConfiguration, 'selectableTimezones' => $selectableTimezones])

        <button type="submit" class="btn btn-primary">Update import configuration</button>
    </form>
@endsection

resources/views/imports/index.blade.php
<?php

use App\Models\ImportConfiguration;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/** @var LengthAwarePaginator&ImportConfiguration[] $importConfigurations */

?>
@extends('layouts.app')

@section('content')
    <h1>Import configurations</h1>

    <a href="{!! route('imports.create') !!}">
        <i class="fa fa-plus-square"></i>
        Create new
    </a>

    <a href="{!! route('imports.deleted') !!}">
        <i class="fa fa-trash-restore"></i>
        Show deleted
    </a>

    <div class="table-responsive">
        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>Method</th>
                <th>Operations</th>
            </tr>

            @forelse($importConfigurations as $importConfiguration)
                <tr>
                    <td>
                        <a href="{!! route('imports.show', $importConfiguration) !!}">{{ $importConfiguration->name }}</a>
                    </td>
                    <td>
                        {{ $importConfiguration->readable_method }}
                    </td>
                    <td>
                        <a href="{!! route('imports.edit', $importConfiguration) !!}" title="Edit..."><i class="fa fa-edit"></i></a>

                        <a href="#" data-toggle="modal" data-target="#deleteImportModal{{ $importConfiguration->id }}" title="Delete..."><i class="fa fa-trash"></i></a>
                        @include('imports._delete', ['importConfiguration' => $importConfiguration])
                    </td>
                </tr>
            @empty
                <tr><td colspan="999">There are no import configurations.</td></tr>
            @endforelse
        </table>

        {!! $importConfigurations->links() !!}
    </div>
@endsection

resources/views/imports/show.blade.php
<?php

use App\Models\ImportConfiguration;

/** @var ImportConfiguration $importConfiguration */

?>
@extends('layouts.app')

@section('content')
    <h1>Import configuration {{ $importConfiguration->name }}</h1>

    <a href="{!! route('imports.edit', $importConfiguration) !!}">
        <i class="fa fa-edit"></i>
        Edit
    </a>

    <a href="#" data-toggle="modal" data-target="#deleteImportModal{{ $importConfiguration->id }}"><i class="fa fa-trash"></i> Delete</a>
    @include('imports._delete', ['importConfiguration' => $importConfiguration])

    @if(!empty($importConfiguration->note))
        <h2>Note</h2>
        <p>
            {!! nl2br(e($importConfiguration->note)) !!}
        </p>
    @endif

    <h2>Attributes</h2>
    <ul>
        <li>Method: {{ $importConfiguration->readable_method }}</li>
        <li>Date format: {{ $importConfiguration->date_format ?? '(default)' }}</li>
        <li>Timezone: {{ $importConfiguration->timezone->getName() }}</li>
    </ul>

    <h2>Parse expression</h2>
    <pre class="text-wrap">{{ $importConfiguration->parse_expression }}</pre>

    <h2>Run this import configuration</h2>
    <form action="{{ route('imports.run', $importConfiguration) }}" method="post" enctype="multipart/form-data">
        @csrf

        <div class="form-group">
            <div class="custom-file col-lg-6">
                <input class="custom-file-input @if ($errors->has('import_file')) is-invalid @endif" type="file" name="import_file" id="import_file" />
                <label class="custom-file-label" for="import_file">Uploaded file (if applicable)</label>
            </div>

            @error('import_file')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>

        <input type="submit" class="btn btn-primary" value="Run!" />
    </form>
@endsection