routes/web.php
<?php

use App\Enums\AllocationViewMode;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'view.variables'], function () {
    Auth::routes();
});

Route::group(['middleware' => ['auth', 'organization', 'view.variables']], function () {
    Route::get('/', 'HomeController@index')
        ->name('home');

    Route::get('/invitations', 'InvitationController@index')
        ->name('invitations.index');
    Route::get('/invitations/create', 'InvitationController@create')
        ->name('invitations.create');
    Route::post('/invitations', 'InvitationController@store')
        ->name('invitations.store');
    Route::delete('/invitations/{maybeExpiredInvitation}', 'InvitationController@delete')
        ->name('invitations.delete');

    Route::get('/preferences', 'PreferencesController@edit')
        ->name('preferences.edit');
    Route::put('/preferences', 'PreferencesController@update')
        ->name('preferences.update');

    Route::get('/organizations', 'OrganizationController@index')
        ->name('organizations.index');
    Route::get('/organizations/create', 'OrganizationController@create')
        ->name('organizations.create');
    Route::get('/organizations/deleted', 'OrganizationController@deleted')
        ->name('organizations.deleted');
    Route::get('/organizations/{organization}', 'OrganizationController@show')
        ->name('organizations.show');
    Route::get('/organizations/{organization}/edit', 'OrganizationController@edit')
        ->name('organizations.edit');
    Route::post('/organizations', 'OrganizationController@store')
        ->name('organizations.store');
    Route::post('/organizations/{trashedOrganization}/restore', 'OrganizationController@restore')
        ->name('organizations.restore');
    Route::post('/organizations/{organization}/switch', 'OrganizationController@switch')
        ->name('organizations.switch');
    Route::put('/organizations/{organization}', 'OrganizationController@update')
        ->name('organizations.update');
    Route::delete('/organizations/{organization}', 'OrganizationController@delete')
        ->name('organizations.delete');

    Route::get('/webhooks', 'WebhookController@index')
        ->name('webhooks.index');
    Route::get('/webhooks/create', 'WebhookController@create')
        ->name('webhooks.create');
    Route::get('/webhooks/{webhook}/edit', 'WebhookController@edit')
        ->name('webhooks.edit');
    Route::post('/webhooks', 'WebhookController@store')
        ->name('webhooks.store');
    Route::put('/webhooks/{webhook}', 'WebhookController@update')
        ->name('webhooks.update');
    Route::delete('/webhooks/{webhook}', 'WebhookController@delete')
        ->name('webhooks.delete');
    Route::post('/webhooks/{webhook}/test', 'WebhookController@test')
        ->name('webhooks.test');

    Route::get('/webhooks/{webhook}', 'WebhookCallController@index')
        ->name('webhookcalls.index');
    Route::get('/webhooks/{webhook}/calls/{call}', 'WebhookCallController@show')
        ->name('webhookcalls.show');

    Route::put('/token', 'Auth\ApiTokenController@update')->name('token.update');

    Route::get('/assets', 'AssetController@index')
        ->name('assets.index');
    Route::get('/assets/create', 'AssetController@create')
        ->name('assets.create');
    Route::get('/assets/deleted', 'AssetController@deleted')
        ->name('assets.deleted');
    Route::get('/assets/{asset:uuid}', 'AssetController@show')
        ->name('assets.show');
    Route::post('/assets', 'AssetController@store')
        ->name('assets.store');
    Route::get('/assets/{asset:uuid}/edit', 'AssetController@edit')
        ->name('assets.edit');
    Route::put('/assets/{asset:uuid}', 'AssetController@update')
        ->name('assets.update');
    Route::delete('/assets/{asset:uuid}', 'AssetController@delete')
        ->name('assets.delete');
    Route::post('/assets/{trashedAsset:uuid}/restore', 'AssetController@restore')
        ->name('assets.restore');
    Route::post('/assets/{trashedAsset:uuid}/forceDelete', 'AssetController@forceDelete')
        ->name('assets.forceDelete');

    Route::get('/assets/{asset:uuid}/prices/create', 'PriceController@create')
        ->name('prices.create');
    Route::post('/assets/{asset:uuid}/prices', 'PriceController@store')
        ->name('prices.store');
    Route::delete('/assets/{asset:uuid}/prices/{price}', 'PriceController@delete')
        ->name('prices.delete');

    Route::get('/assets/{asset:uuid}/transactions/create', 'TransactionController@create')
        ->name('transactions.create');
    Route::post('/assets/{asset:uuid}/transactions', 'TransactionController@store')
        ->name('transactions.store');
    Route::get('/assets/{asset:uuid}/transactions/{transaction}/edit', 'TransactionController@edit')
        ->name('transactions.edit');
    Route::put('/assets/{asset:uuid}/transactions/{transaction}', 'TransactionController@update')
        ->name('transactions.update');
    Route::delete('/assets/{asset:uuid}/transactions/{transaction}', 'TransactionController@delete')
        ->name('transactions.delete');

    Route::get('/assets/{asset:uuid}/values/create', 'ValueController@create')
        ->name('values.create');
    Route::post('/assets/{asset:uuid}/values', 'ValueController@store')
        ->name('values.store');

    Route::get('/allocations', 'AllocationController@index')
        ->name('allocations.index');
    Route::get('/allocations/create', 'AllocationController@create')
        ->name('allocations.create');
    Route::get('/allocations/deleted', 'AllocationController@deleted')
        ->name('allocations.deleted');
    Route::get('/allocations/{allocation}/{view}', 'AllocationController@show')
        ->where('view', implode('|', array_map(fn(AllocationViewMode $x) => $x->value, AllocationViewMode::cases())))
        ->name('allocations.show');
    Route::get('/allocations/{allocation}/value', 'AllocationController@value')
        ->name('allocations.value');
    Route::get('/allocations/{allocation}/edit', 'AllocationController@edit')
        ->name('allocations.edit');
    Route::post('/allocations', 'AllocationController@store')
        ->name('allocations.store');
    Route::post('/allocations/{trashedAllocation}/restore', 'AllocationController@restore')
        ->name('allocations.restore');
    Route::put('/allocations/{allocation}', 'AllocationController@update')
        ->name('allocations.update');
    Route::delete('/allocations/{allocation}', 'AllocationController@delete')
        ->name('allocations.delete');

    Route::get('/allocations/{allocation}/check/edit', 'AllocationCheckController@edit')
        ->name('allocations.check.edit');
    Route::put('/allocations/{allocation}/check', 'AllocationCheckController@update')
        ->name('allocations.check.update');
    Route::delete('/allocations/{allocation}/check', 'AllocationCheckController@delete')
        ->name('allocations.check.delete');

    Route::get('/imports', 'ImportController@index')
        ->name('imports.index');
    Route::get('/imports/create', 'ImportController@create')
        ->name('imports.create');
    Route::get('/imports/deleted', 'ImportController@deleted')
        ->name('imports.deleted');
    Route::get('/imports/{importConfiguration}', 'ImportController@show')
        ->name('imports.show');
    Route::get('/imports/{importConfiguration}/edit', 'ImportController@edit')
        ->name('imports.edit');
    Route::post('/imports', 'ImportController@store')
        ->name('imports.store');
    Route::post('/imports/{trashedImportConfiguration}/restore', 'ImportController@restore')
        ->name('imports.restore');
    Route::post('/imports/{importConfiguration}/run', 'ImportController@run')
        ->name('imports.run');
    Route::put('/imports/{importConfiguration}', 'ImportController@update')
        ->name('imports.update');
    Route::delete('/imports/{importConfiguration}', 'ImportController@delete')
        ->name('imports.delete');

    Route::get('/executions', 'ExecutionController@index')
        ->name('executions.index');
    Route::get('/executions/{execution}', 'ExecutionController@show')
        ->name('executions.show');
    Route::delete('/executions/{execution}', 'ExecutionController@delete')
        ->name('executions.delete');

    Route::get('/exports', 'ExportController@index')
        ->name('exports.index');
    Route::get('/exports/create', 'ExportController@create')
        ->name('exports.create');
    Route::post('/exports/run', 'ExportController@run')
        ->name('exports.run');

    Route::post('/display/graph', 'Display\DisplayController@setGraphControls')
        ->name('display.graph');

    Route::get('/notifications', 'NotificationController@index')
        ->name('notifications.index');
    Route::get('/notifications/{notification}', 'NotificationController@show')
        ->name('notifications.show');

    Route::group(['prefix' => '/admin', 'middleware' => ['can:admin-actions']], function () {
        Route::get('/', 'Admin\HomeController@index')
            ->name('admin.home');

        Route::get('/users', 'Admin\UserController@index')
            ->name('admin.users.index');
        Route::get('/users/{user}', 'Admin\UserController@show')
            ->name('admin.users.show');
        Route::post('/users/{user}/promote', 'Admin\UserController@promote')
            ->name('admin.users.promote');
        Route::post('/users/{user}/demote', 'Admin\UserController@demote')
            ->name('admin.users.demote');

app/Models/Webhook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Webhook extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'uri',
    ];

    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    public function allocations(): HasMany
    {
        return $this->hasMany(Allocation::class, 'check_webhook_id');
    }

    public function calls(): HasMany
    {
        return $this->hasMany(WebhookCall::class);
    }
}

app/Http/Controllers/WebhookController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\SendWebhook;
use App\Models\Webhook;
use Exception;
use Illuminate\Http\Request;
use Session;
use Throwable;

class WebhookController extends Controller
{
    public function index(Request $request)
    {
        $organization = $this->getOrganization($request);

        $this->authorize('viewAny', [Webhook::class, $organization]);

        $webhooks = $organization->webhooks()
            ->withCount('allocations')
            ->withCount('calls')
            ->orderBy('uri')
            ->paginate();

        return view('webhooks.index', [
            'webhooks' => $webhooks,
        ]);
    }

    public function create(Request $request)
    {
        $organization = $this->getOrganization($request);

        $this->authorize('create', [Webhook::class, $organization]);

        $webhook = new Webhook();

        $webhook->fill(Session::getOldInput());

        return view('webhooks.create', [
            'webhook' => $webhook,
        ]);
    }

    /**
     * @throws Throwable
     */
    public function store(Request $request)
    {
        $organization = $this->getOrganization($request);

        $this->authorize('create', [Webhook::class, $organization]);

        $data = $request->validate([
            'name' => ['required', 'max:255'],
            'uri' => ['required', 'max:255', 'url'],
        ]);

        $webhook = new Webhook($data);
        $webhook->shared_secret = base64_encode(random_bytes(24));
        $request->session()->flash('shared_secret', $webhook->shared_secret);

        $webhook->organization()->associate($organization);

        $webhook->saveOrFail();

        return redirect(route('webhooks.index'));
    }

    public function edit(Webhook $webhook)
    {
        $this->authorize('update', $webhook);

        $webhook->fill(Session::getOldInput());

        return view('webhooks.edit', [
            'webhook' => $webhook,
        ]);
    }

    /**
     * @throws Throwable
     */
    public function update(Request $request, Webhook $webhook)
    {
        $this->authorize('update', $webhook);

        $data = $request->validate([
            'name' => ['required', 'max:255'],
            'uri' => ['required', 'max:255', 'url'],
        ]);

        $webhook->fill($data);
        $webhook->saveOrFail();

        return redirect(route('webhooks.index'));
    }

    /**
     * @throws Exception
     */
    public function delete(Webhook $webhook)
    {
        $this->authorize('delete', $webhook);

        foreach ($webhook->allocations as $allocation) {
            $allocation->unsetCheck();
            $allocation->save();
        }

        $webhook->delete();

        return redirect(route('webhooks.index'));
    }

    public function test(Request $request, Webhook $webhook)
    {
        $this->authorize('test', $webhook);

        $job = new SendWebhook($webhook, 'This is a sample message', 'text/plain');
        $job->tries = 1; // Contrary to a system-sent webhook call, we don't need retries when manually testing...
        $this->dispatch($job);

        $request->session()->flash('test_success', 'The test request has been dispatched. It may take a couple of seconds before it completes. Note that automatic retries on failure have been disabled on this request.');

        return redirect()->back();
    }
}

resources/views/webhooks/_delete.blade.php
<?php

use App\Models\Webhook;

/** @var Webhook $webhook */

?>
<div class="modal" id="deleteWebhookModal{{ $webhook->id }}" tabindex="-1" role="dialog" aria-labelledby="deleteWebhookModalLabel{{ $webhook->id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteWebhookModalLabel{{ $webhook->id }}">Delete webhook '{{ $webhook->name }}'</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this webhook? You cannot undo this.</p>
                <p>Webhook URI: {{ $webhook->uri }}</p>
                <p>{{ trans_choice('webhook.allocations_count', $webhook->allocations_count) }}.</p>
                <p>If there any allocations use this webhook, their check configuration will be cleared.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                <form action="{{ route('webhooks.delete', $webhook) }}" method="post">
                    @method('delete')
                    @csrf
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/webhooks/_form.blade.php
<?php

use App\Models\Webhook;

/** @var Webhook $webhook */

?>
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" id="name" value="{{ $webhook->name }}" required />
    @error('name')
        <div class="invalid-feedback">{{ $message }}</div>
    @enderror
</div>

<div class="form-group">
    <label for="uri">URI</label>
    <input type="url" class="form-control @if ($errors->has('uri')) is-invalid @endif" name="uri" id="uri" value="{{ $webhook->uri }}" required />
    @error('uri')
        <div class="invalid-feedback">{{ $message }}</div>
    @enderror
</div>

resources/views/webhooks/create.blade.php
<?php

use App\Models\Webhook;

/** @var Webhook $webhook */

?>
@extends('layouts.app')

@section('content')
    <h1>New webhook</h1>

    <form class="needs-validation" action="{!! route('webhooks.store') !!}" method="post" novalidate>
        @csrf

        @include('webhooks._form', ['webhook' => $webhook])

        <button type="submit" class="btn btn-primary">Create webhook</button>
    </form>
@endsection

resources/views/webhooks/edit.blade.php
<?php

use App\Models\Webhook;

/** @var Webhook $asset */

?>
@extends('layouts.app')

@section('content')
    <h1>Edit webhook</h1>

    <form class="needs-validation" action="{!! route('webhooks.update', $webhook) !!}" method="post" novalidate>
        @method('put')
        @csrf

        @include('webhooks._form', ['webhook' => $webhook])

        <button type="submit" class="btn btn-primary">Update webhook</button>
    </form>
@endsection

resources/views/webhooks/index.blade.php
<?php

use App\Models\Webhook;

/** @var Webhook[] $webhooks */

?>
@extends('layouts.app')

@section('content')
    <h1>Webhooks</h1>

    <a href="{!! route('webhooks.create') !!}">
        <i class="fa fa-plus-square"></i>
        Create new
    </a>

    @if(Session::has('shared_secret'))
        <div class="alert alert-success">
            Webhook created. The shared secret is {{ Session::get('shared_secret') }}. This value will only be displayed once.
        </div>
    @endif

    @if(Session::has('test_success'))
        <div class="alert alert-success">
            {{ Session::get('test_success') }}
        </div>
    @endif

    <div class="table-responsive">
        <table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>URI</th>
                <th>Calls</th>
                <th>Operations</th>
            </tr>

            @forelse($webhooks as $webhook)
                <tr>
                    <td>
                        <a href="{{ route('webhookcalls.index', $webhook) }}">{{ $webhook->name }}</a>
                    </td>
                    <td>
                        {{ $webhook->uri }}
                    </td>
                    <td>
                        {{ $webhook->calls_count }}
                    </td>
                    <td>
                        <a href="{!! route('webhooks.edit', $webhook) !!}" title="Edit..."><i class="fa fa-edit"></i></a>

                        <a href="#" data-toggle="modal" data-target="#deleteWebhookModal{{ $webhook->id }}" title="Delete..."><i class="fa fa-trash"></i></a>
                        @include('webhooks._delete', ['webhook' => $webhook])

                        <form method="post" action="{{ route('webhooks.test', $webhook) }}">
                            @csrf
                            <button type="submit" class="btn btn-sm btn-primary">Test</button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr><td colspan="999">There are no webhooks.</td></tr>
            @endforelse
        </table>

        {!! $webhooks->links() !!}
    </div>
@endsection